### ISSUE TITLE
KeyError: 'pass_ticket'

### ISSUE THREAD

**Issue by xixiaoyao** [wzyonggege/wechat-wxpy#1]
Traceback (most recent call last):
  File "wx.py", line 4, in <module>
    base_bot = Bot(True)
  File "/Users/xiaoxi/opt/miniconda3/lib/python3.7/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/Users/xiaoxi/opt/miniconda3/lib/python3.7/site-packages/itchat/components/register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/Users/xiaoxi/opt/miniconda3/lib/python3.7/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/Users/xiaoxi/opt/miniconda3/lib/python3.7/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by cuiwanzhi** [comment]
Traceback (most recent call last):
  File "C:\Users\23683\Desktop\python\weixinjiqiren\wechat-wxpy-master\main.py", line 4, in <module>
    base_bot = Bot(True)
  File "C:\Users\23683\AppData\Local\Programs\Python\Python37-32\lib\site-packages\wxpy\api\bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "C:\Users\23683\AppData\Local\Programs\Python\Python37-32\lib\site-packages\itchat\components\register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Users\23683\AppData\Local\Programs\Python\Python37-32\lib\site-packages\itchat\components\login.py", line 66, in login
    self.show_mobile_login()
  File "C:\Users\23683\AppData\Local\Programs\Python\Python37-32\lib\site-packages\itchat\components\login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by cuiwanzhi** [comment]
请问您解决了这个问题了吗？

**Comment by Autbam** [comment]
求更新啊。太老了
